name: flashCamera
description: A Flutter plugin for getting information about and controlling the
  camera on Android and iOS. Supports previewing the camera feed and capturing images.
version: 0.0.1
authors:
homepage:
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^0.4.1
  video_player: ^0.5.2

flutter:
  plugin:
    androidPackage: io.flutter.plugins.camera
    pluginClass: CameraPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
